openapi: 3.0.1
info:
  title: Outlook Email Summarizer API
  description: >-
    An API that accepts a Microsoft Outlook message ID and returns a concise
    summary of the email's content. This is designed to be used as an action
    in a custom GPT.
  version: 1.0.0
servers:
  # The server URL should be the publicly accessible endpoint where your
  # FastAPI service is hosted. You will need to replace this with your actual URL.
  # For local testing, you can use ngrok or a similar tunneling service.
  - url: http://ec2-52-43-205-252.us-west-2.compute.amazonaws.com:8000
    description: Production Server
paths:
  /messages/{msg_id}/summary:
    get:
      summary: Summarize a Single Email
      description: >-
        Fetches a single email by its Microsoft Graph message ID, generates a
        summary, and returns it.
      operationId: summarizeSingleEmail
      parameters:
        - name: msg_id
          in: path
          required: true
          description: The unique and immutable ID of the email message from Microsoft Graph API.
          schema:
            type: string
          example: AAMkAGI1ZTMx...
      responses:
        '200':
          description: Successfully retrieved and generated the email summary.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummarizeResponse'
        '404':
          description: Not Found - No email message could be found for the provided 'msg_id'.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: Bad Gateway - An error occurred while communicating with an upstream API (e.g., Microsoft Graph).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /summaries/:
    post:
      summary: Summarize Multiple Emails
      description: Creates a single digest summary from a list of provided email message IDs.
      operationId: summarizeBulk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummarizeBulkRequest'
      responses:
        '200':
          description: Successfully generated the digest summary.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummarizeDigestResponse'
  /summaries/daily:
    get:
      summary: Get Daily Summary Digest
      description: Generates a digest summary of all emails received in the last 24 hours.
      operationId: summarizeDaily
      responses:
        '200':
          description: Successfully generated the daily digest.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummarizeDigestResponse'

components:
  schemas:
    SummarizeResponse:
      type: object
      properties:
        summary:
          type: string
        message_id:
          type: string
        cached:
          type: boolean
        llm_provider:
          type: string
    SummarizeBulkRequest:
      type: object
      properties:
        message_ids:
          type: array
          items:
            type: string
    SummarizeDigestResponse:
      type: object
      properties:
        digest:
          type: string
        llm_provider:
          type: string
    Error:
      type: object
      properties:
        detail:
          type: string
          description: A clear, human-readable error message.
      required:
        - detail
      example:
        detail: "Email with message_id 'xyz' not found." 